package cli

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"sort"
	"strings"
	"testing"
	"time"
)

func TestCompletionWithoutStoreAndShellSyntax(t *testing.T) {
	for _, shell := range []string{"bash", "zsh", "fish"} {
		t.Run(shell, func(t *testing.T) {
			var out, diagnostics bytes.Buffer
			a := App{Out: &out, Err: &diagnostics, Getenv: func(string) string { return "/absent/fulla-fixture" }}
			if code := a.Main([]string{"completion", shell}); code != 0 {
				t.Fatalf("generation failed %d: %s", code, diagnostics.String())
			}
			binary, err := exec.LookPath(shell)
			if err != nil {
				t.Skipf("%s unavailable for shell syntax acceptance", shell)
			}
			cmd := exec.Command(binary, "-n")
			cmd.Stdin = bytes.NewReader(out.Bytes())
			if result, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("invalid shell script: %v %s", err, result)
			}
		})
	}
}

func TestBashCompletionFindsGroupedCommandsAfterGlobalOptions(t *testing.T) {
	bash, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash unavailable")
	}
	var script bytes.Buffer
	a := App{Out: &script}
	if code := a.Main([]string{"completion", "bash"}); code != 0 {
		t.Fatal(code)
	}
	script.WriteString(`
COMP_WORDS=(fulla --store '/fixture with spaces' --json peer r)
COMP_CWORD=5
_fulla
printf '%s\n' "${COMPREPLY[@]}"
COMP_WORDS=(fulla git -- '')
COMP_CWORD=3
_fulla
[ "${#COMPREPLY[@]}" -eq 0 ] || exit 72
`)
	command := exec.Command(bash)
	command.Stdin = &script
	out, err := command.CombinedOutput()
	if err != nil || string(out) != "rotate\nremove\n" {
		t.Fatalf("wrong completion: %v %q", err, out)
	}
}

func TestCompletionRejectsJSONAndUnknownShell(t *testing.T) {
	for _, args := range [][]string{{"completion", "bash", "--json"}, {"completion", "unknown", "--json"}} {
		var out bytes.Buffer
		a := App{Out: &out}
		if code := a.Main(args); code != 2 || !strings.Contains(out.String(), "fulla.cli/v1") || strings.Contains(out.String(), "compdef") {
			t.Fatalf("mixed shell output and JSON: %d %s", code, out.String())
		}
	}
}

// Exercise Fish's actual completion engine rather than matching generated text.
func TestFishCompletionBehavior(t *testing.T) {
	fish, err := exec.LookPath("fish")
	if err != nil {
		if os.Getenv("FULLA_REQUIRE_FISH") == "1" {
			t.Fatal("fish is required for this acceptance gate")
		}
		t.Skip("fish unavailable")
	}
	var generated bytes.Buffer
	a := App{Out: &generated}
	if code := a.Main([]string{"completion", "fish"}); code != 0 {
		t.Fatal(code)
	}
	for _, tc := range []struct {
		line string
		want []string
	}{
		{"fulla pe", []string{"peer"}},
		{"fulla --store '/fixture with spaces' --json peer r", []string{"remove", "rotate"}},
		{"fulla --config=/absent/config backup re", []string{"restore"}},
		{"fulla completion f", []string{"fish"}},
		{"fulla --store ", nil},
		{"fulla git -- ", nil},
		{"fulla run -- tool --j", nil},
	} {
		t.Run(tc.line, func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			cmd := exec.CommandContext(ctx, fish, "--no-config", "-c", generated.String()+"\ncomplete -C $argv[1]", "--", tc.line)
			cmd.Env = []string{"PATH=/usr/bin:/bin", "HOME=" + t.TempDir(), "XDG_CONFIG_HOME=" + t.TempDir()}
			out, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("fish completion: %v: %s", err, out)
			}
			var got []string
			for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
				if line != "" {
					got = append(got, strings.SplitN(line, "\t", 2)[0])
				}
			}
			sort.Strings(got)
			if strings.Join(got, "\n") != strings.Join(tc.want, "\n") {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}
